version: 2.1

orbs:
  moul: moul/build@1.16.0 # https://github.com/moul/build

jobs:
  test-go-binary:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/moul.io/rules.mk
    environment:
      - GO111MODULE=on
    steps:
      - checkout
      - run: cd test/go-binary; make build
      - run: cd test/go-binary; make install
      - moul/install_golangci-lint
      - run: cd test/go-binary; make test
      - run: cd test/go-binary; make bumpdeps
  test-go-library:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/moul.io/rules.mk
    environment:
      - GO111MODULE=on
    steps:
      - checkout
      - run: cd test/go-library; make build
      - moul/install_golangci-lint
      - run: cd test/go-library; make test
      - run: cd test/go-library; make bumpdeps
  test-docker:
    executor: moul/docker
    steps:
      - checkout
      - setup_remote_docker
      - run: apk add --no-cache make
      - run: cd test/docker; make build
  test-go-binary-and-docker:
    docker:
      - image: circleci/golang:1.14
    environment:
      - GO111MODULE=on
    working_directory: /go/src/moul.io/rules.mk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
      - run: cd test/go-binary-and-docker; make build
      - run: cd test/go-binary-and-docker; make install
      - moul/install_golangci-lint
      - run: cd test/go-binary-and-docker; make test
      - run: cd test/go-binary-and-docker; make bumpdeps
  test-go-binary-and-docker--only-golang:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/moul.io/rules.mk
    environment:
      - DOCKER_IMAGE=none
      - GO111MODULE=on
    steps:
      - checkout
      - run: cd test/go-binary-and-docker; make build
      - run: cd test/go-binary-and-docker; make install
      - moul/install_golangci-lint
      - run: cd test/go-binary-and-docker; make test
      - run: cd test/go-binary-and-docker; make bumpdeps

workflows:
  main:
    jobs:
      - test-go-binary
      - test-go-library
      - test-docker
      - test-go-binary-and-docker
      - test-go-binary-and-docker--only-golang
